site_name: DIP Solver Documentation

theme:
    name: material
    features:
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.code.select
        - header.autohide
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.indexes
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.prune
        - navigation.sections
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch-off
              name: Switch to system preference
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue grey
          accent: blue
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode
    font:
        text: Roboto
        code: Roboto Mono

plugins:
    - search
    - mkdocstrings:
          options:
              show_source: true

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.caret
    - pymdownx.highlight:
          auto_title: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true
          slugify: !!python/object/apply:pymdownx.slugs.slugify
              kwds:
                  case: lower
    - pymdownx.tasklist:
          custom_checkbox: true

nav:
    - Home: "index.md"
    - Helper: "helper.md"
    - Operations: "operations.md"
    - Segmentation: "segmentation.md"
    - Neighborhood Operations: "neighborhood_operations.md"
    - Morphology: "morphology.md"
    - Plugins: "plugins.md"
